name: Rust

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  schedule: [cron: "0 */5 * * *"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: make test

    - name: Archive test log
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: test log
        path: /tmp/test_crossfire.log

    - name: cleanup logs
      run: /bin/rm /tmp/test_crossfire.log

    - name: Run tests with --release
      run: make test_release

    - name: Archive test log
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: test log
        path: /tmp/test_crossfire.log
